[tool.black]
# Python版本
target-version = ['py39', 'py310']

# 每行最大字符数
line-length = 100

# 包含的文件模式
include = '\.pyi?$'

# 排除的文件和目录
exclude = '''
/(
    \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
  | migrations
  | __pycache__
  | models/pretrained
  | models/finetuned
  | data/raw
  | data/processed
)/
'''

# 跳过字符串标准化（保持原有引号风格）
skip-string-normalization = false

# 强制单引号字符串
skip-magic-trailing-comma = false