# 法智导航项目配置文件
# ===========================================

# 项目基础信息
project:
  name: "法智导航"
  version: "1.0.0"
  description: "智能法律匹配与个性化咨询系统"
  
# 数据路径配置
data:
  # 原始数据路径
  raw_data_dir: "./data/raw"
  raw_laws_file: "raw_laws(1).csv"
  raw_cases_file: "raw_cases(1).csv"
  mapping_file: "精确映射表.csv"
  
  # 处理后数据路径
  processed_data_dir: "./data/processed"
  unified_knowledge_base: "legal_knowledge_base.csv"
  
  # 数据清洗参数
  min_text_length: 10
  max_text_length: 10000
  remove_duplicates: true

# 模型配置
model:
  # 第一阶段：预训练模型
  pretrained_model_name: "shibing624/text2vec-base-chinese"
  # 备选模型
  alternative_models:
    - "sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2"
    - "GanymedeNil/text2vec-large-chinese"
  
  # 向量维度
  embedding_dim: 768
  max_sequence_length: 512
  
  # 模型保存路径
  model_save_dir: "./models"
  pretrained_dir: "./models/pretrained"
  finetuned_dir: "./models/finetuned"

# 向量检索配置
retrieval:
  # FAISS索引配置
  index_type: "IndexFlatIP"  # 内积搜索
  index_file: "legal_db.index"
  
  # 检索参数
  top_k: 10
  search_batch_size: 32
  
  # 性能优化
  use_gpu: false  # 第一阶段使用CPU
  nprobe: 32

# API服务配置
api:
  # 服务配置
  host: "0.0.0.0"
  port: 8000
  debug: true
  reload: true
  
  # 接口参数
  max_query_length: 500
  default_top_k: 10
  timeout_seconds: 30
  
  # 跨域配置
  cors_origins:
    - "http://localhost:3000"
    - "http://127.0.0.1:3000"

# 日志配置
logging:
  level: "INFO"
  format: "{time:YYYY-MM-DD HH:mm:ss} | {level} | {name}:{function}:{line} - {message}"
  log_file: "./logs/app.log"
  max_file_size: "100 MB"
  retention: "7 days"

# 性能监控
performance:
  # 响应时间阈值 (秒)
  api_response_threshold: 2.0
  model_inference_threshold: 1.0
  
  # 系统资源监控
  monitor_cpu: true
  monitor_memory: true
  
  # 统计信息保存
  stats_save_interval: 300  # 5分钟

# 缓存配置
cache:
  # 向量缓存
  enable_embedding_cache: true
  cache_size: 10000
  
  # 查询结果缓存
  enable_result_cache: true
  cache_ttl: 3600  # 1小时

# 第二阶段预设配置 (未来使用)
training:
  # 训练参数
  batch_size: 16
  learning_rate: 2e-5
  epochs: 3
  warmup_steps: 100
  
  # 数据集分割
  train_ratio: 0.8
  val_ratio: 0.1
  test_ratio: 0.1
  
  # 损失函数
  loss_function: "MultipleNegativesRankingLoss"
  
  # 评估指标
  evaluation_metrics:
    - "accuracy@1"
    - "accuracy@5"
    - "accuracy@10"
    - "mrr"  # Mean Reciprocal Rank

# 环境配置
environment:
  # Python环境
  python_version: ">=3.9"
  
  # GPU配置 (第二阶段)
  cuda_available: false
  gpu_memory_threshold: 0.8
  
  # 内存配置
  max_memory_usage: "8GB"
  
# 开发配置
development:
  # 测试数据
  test_data_size: 100
  sample_queries:
    - "房屋租赁合同违约"
    - "交通事故责任认定"
    - "劳动争议仲裁程序"
  
  # 调试选项
  debug_mode: true
  verbose_logging: true
  save_intermediate_results: true